spring:
  application:
    name: mail-sys
  mail:
    host: smtp.163.com
    username: 15216619538@163.com
    password: 125263ww
    default-encoding: UTF-8
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/spring_cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncodeing=utf-8&useSSL=false
      username: root
      password: root

logging:
  level:
    root: debug

server:
  port: 8080

wechat:
  token: 960812ww
  appid: wx83ca98555f482b1d
  appsecret: 7c81dd372a5bde3f13f9cdda1b7dff35
  encodingAESKey: TDmCawn758p7Y2vo7JfbERphchNo4RCiCDUhksBL29z
  assessTokenIp:  https://api.weixin.qq.com/cgi-bin/token?grant_type={grant_type}&appid={appid}&secret={secret}
  sendTemplateMsgIp: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token={access_token}