spring:
  application:
    name: mail-sys
  mail:
    host: smtp.163.com
    username: 15216619538@163.com
    password: 125263ww
    default-encoding: UTF-8

logging:
  level:
    root: debug

server:
  port: 8080

wechat:
  token: 960812ww
  encodingAESKey: TDmCawn758p7Y2vo7JfbERphchNo4RCiCDUhksBL29z
